name: Add default label

on:
  issues:
    types: [opened]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: d-i-bondarenko/project-labeler@v0.2.0
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
