name: Create a new pull request on push

on: push
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create PR
        uses: funivan/github-autopr@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
