name: Update linked issue status according to PR state

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  sync-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Get Linked Issues Action
        uses: kin/gh-action-get-linked-issues@v2.0
        id: linked-issues
        with:
          access-token: ${{ secrets.GH_TOKEN }}
      
      - name: Move Issue to In Review Column
        if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
        uses: kin/gh-action-move-issues-to-column@v1.0
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          target-column: "In Review"
          issues: ${{ steps.linked-issues.outputs.issues }}

      - name: Move Issue to In QA Column
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
        uses: kin/gh-action-move-issues-to-column@v1.0
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          target-column: "In QA"
          issues: ${{ steps.linked-issues.outputs.issues }}
      
#       - name: Get Linked Issue Script
#         if: github.event_name == 'issue_comment' && github.event.issue.pull_request
#         run: |
#           echo "pr_id=${{ github.event.issue.number }}" >> $GITHUB_ENV
        
      - name: Move Issue to In Deploy Column
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, 'media.giphy.com') && github.event.issue.pull_request
        uses: kin/gh-action-move-issues-to-column@v1.0
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          target-column: "In Deploy"
          issues: ${{ steps.linked-issues.outputs.issues }}
