name: Update linked issue status before and after review

on:
  pull_request:
    types: [review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Linked Issues Action
        uses: kin/gh-action-get-linked-issues@v1.0
        id: linked-issues
        with:
          access-token: ${{ secrets.GH_TOKEN }}
      
      - name: Move Issue to In Review Column
        if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
        uses: kin/gh-action-move-issues-to-column@v1.0
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          target-column: "In Review"
          issues: ${{ steps.linked-issues.outputs.issues }}

      - name: Move Issue to In QA Column
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
        uses: kin/gh-action-move-issues-to-column@v1.0
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          target-column: "In QA"
          issues: ${{ steps.linked-issues.outputs.issues }}
